run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck     # Проверяет, что вы не забыли обработать if err != nil
    - govet        # Ищет подозрительные конструкции (например, неправильные аргументы в логах)
    - staticcheck  # Находит скрытые баги и устаревший код
    - unused       # Подсвечивает переменные и функции, которые вы создали, но забыли использовать
    - bodyclose    # Важно для сети: проверяет, что вы не забыли закрыть resp.Body
    - asasalint    # Специальный линтер для Zap! Проверяет, что вы правильно передаете поля pass-by-value

issues:
  exclude-use-default: false
