syntax = "proto3";

package user.v1;
option go_package = "test-project/api/gen/user;userv1"; 
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";  
 

service UserService{
    rpc Register(RegisterRequest) returns(RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Logout(LogoutRequest) returns (LogoutResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
    rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
    rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

message User{
    string user_id = 1 [
        (validate.rules).string.uuid = true
    ];
    string username = 2[
        (validate.rules).string = {
            min_len: 3,
            max_len: 50,
            pattern: "^[a-zA-Z0-9_-]+$"
        }
    ];
    string email = 3[
        (validate.rules).string.email = true
    ];
    Role role = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp updated_at = 6;
}
enum Role {
    ROLE_UNSPECIFIED = 0;
    ROLE_USER = 1;
    ROLE_ADMIN = 2;
    ROLE_GUEST = 3;
}

message RegisterRequest {
    string username = 1[
        (validate.rules).string = {
            min_len: 3,
            max_len: 50,
            pattern: "^[a-zA-Z0-9_-]+$"
        }
    ];
    string email = 2 [
        (validate.rules).string.email = true
    ];
    string password = 3[
        (validate.rules).string = {
            min_len: 8,
            max_len: 72
        }
    ];
} 

message RegisterResponse{
    string user_id = 1; //uuid
    string access_token = 2;
    string refresh_token = 3;
}

message LoginRequest { 
    string email = 1[
        (validate.rules).string.email = true
    ]; 
    string password = 2[
        (validate.rules).string = {
            min_len: 8,
            max_len: 72
        }
    ];
}
message LoginResponse{
    string access_token = 1;
    string refresh_token = 2;
}

message LogoutRequest{
    string refresh_token = 1[
        (validate.rules).string = {
            min_len: 1
        }
    ];
}
message LogoutResponse {
}

message GetUserRequest  {
    string user_id = 1[
        (validate.rules).string.uuid = true
    ];
}

message GetUserResponse{
  string user_id = 1;
  string username = 2;
  string email = 3; 
  Role role = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message ValidateTokenRequest{
    string access_token = 1 [
        (validate.rules).string = {
            min_len: 1
        }
    ]; 
}

message ValidateTokenResponse {
  string user_id = 1;
  Role role = 2;
}

message RefreshTokenRequest{
    string refresh_token = 1 [
        (validate.rules).string = {
            min_len: 1
        }
    ];
}

message RefreshTokenResponse{
    string access_token = 1;
    string refresh_token = 2;
}