syntax = "proto3";

package spot.v1;

option go_package = "test-project/api/gen/spot;spotv1";

import "common/money.proto";

import "google/protobuf/timestamp.proto";
import "validate/validate.proto";  
 


service SpotInstrumentService {
  rpc ListMarkets(ListMarketsRequest) returns (ListMarketsResponse); 
  rpc GetMarket(GetMarketRequest) returns (GetMarketResponse); 
  rpc DisableMarket(DisableMarketRequest) returns (DisableMarketResponse);
}

message Market{
  string market_id = 1[
      (validate.rules).string = {
          pattern: "^[A/Z]+-[A/Z]+$" 
      } 
  ];
  string name = 2; 
  string base_asset = 3; 
  string quote_asset = 4; 
  bool enabled = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  common.v1.Money price = 8;
}

message ListMarketsRequest {
    int32 page_size = 1 [
        (validate.rules).int32 = {
            gte: 1,    
            lte: 100  
        }
    ];
    string page_token = 2; 
}

message ListMarketsResponse {
  repeated Market markets = 1; 
  string next_page_token = 2;
}

message GetMarketRequest {
    string market_id = 1 [
        (validate.rules).string = {
            pattern: "^[A/Z]+-[A/Z]+$"  
        }
    ];
}
message GetMarketResponse{
  Market market = 1;
}


message DisableMarketRequest {
  string market_id = 1[
      (validate.rules).string = {
          pattern: "^[A/Z]+-[A/Z]+$" 
      } 
  ];
}

message DisableMarketResponse {
  Market market = 1;
}