syntax = "proto3";

package user.v1;
import "google/protobuf/timestamp.proto";
// import "validate/validate.proto";

option go_package = "grpc-exchange/gen/user;userv1";
//весь user_id должен быть uuid 

service UserService {
  rpc GetUser(GetUserRequest) returns (User);

  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);

  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse); 
}

message User {
  string user_id = 1;  //uuid [(validate.rules).string.uuid = true]; -  не работает
  string username = 2;
  string email = 3;
  string role = 4;
  bool active = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message GetUserRequest {
  string user_id = 1;
}


message RegisterRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message RegisterResponse {
  string user_id = 1;
  string token = 2;        
  string refresh_token = 3; 
  string message = 4;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string user_id = 1;
  string token = 2;
  string refresh_token = 3; 
  string message = 4;
}

message LogoutRequest {
  string user_id = 1;
  string refresh_token = 2; 
}

message LogoutResponse {
  string message = 1;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string token = 1;
  string refresh_token = 2;
  string message = 3;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  string user_id = 1;
  bool valid = 2; //через statusCode передать (либо доп)
  string role = 3; 
}

//сделать протовалидацию (page(всех протофайлов))